from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


class PRGenerator:
    """Pull Request 生成器

    根据重构结果和测试报告，自动生成包含变更说明的 PR。
    """

    def __init__(self, config: dict[str, Any]):
        self.config = config
        self.branch_prefix = config.get("branch_prefix", "refactor/ops-agent")
        self.auto_merge = config.get("auto_merge", False)
        self.reviewers = config.get("reviewers", [])

    def generate(
        self,
        repo_url: str,
        refactored_code: dict[str, str],
        reports: dict[str, Any],
    ) -> dict[str, Any]:
        """生成 PR

        Args:
            repo_url: 目标仓库 URL
            refactored_code: 重构后的代码
            reports: 各阶段报告

        Returns:
            PR 信息
        """
        branch_name = self._generate_branch_name()
        pr_title = self._generate_title(refactored_code)
        pr_body = self._generate_body(reports, refactored_code)

        logger.info("Generated PR: %s", pr_title)

        return {
            "repo_url": repo_url,
            "branch_name": branch_name,
            "title": pr_title,
            "body": pr_body,
            "files_changed": len(refactored_code),
            "reviewers": self.reviewers,
            "auto_merge": self.auto_merge,
            "status": "generated",
        }

    def _generate_branch_name(self) -> str:
        """生成分支名称"""
        from datetime import datetime
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        return f"{self.branch_prefix}-{timestamp}"

    def _generate_title(self, refactored_code: dict) -> str:
        """生成 PR 标题"""
        count = len(refactored_code)
        return f"[ops-agent] Refactor {count} ops scripts for compliance and security"

    def _generate_body(self, reports: dict, refactored_code: dict) -> str:
        """生成 PR 描述"""
        techdebt = reports.get("techdebt", {})
        security = reports.get("security", {})
        test = reports.get("test", {})

        body = f"""## Automated Refactoring PR

Generated by OpenClaw Ops Agent.

### Changes Summary

- **Files refactored**: {len(refactored_code)}
- **Security issues resolved**: {security.get('issues_fixed', 0)}
- **Tech debt items addressed**: {len(techdebt)}

### Security Baseline

| Check | Status |
|-------|--------|
| Hardcoded secrets | {"PASS" if not security.get('findings') else "NEEDS_REVIEW"} |
| ACL rules | {"DYNAMIC" if security.get('acl_externalized') else "HARDCODED"} |
| Exception handling | {"PASS" if security.get('exception_coverage', 100) >= 90 else "PARTIAL"} |

### Test Results

| Test | Status |
|------|--------|
| Unit tests | {"PASS" if test.get('unit_passed', False) else "FAIL"} |
| Integration tests | {"PASS" if test.get('integration_passed', False) else "FAIL"} |
| Device simulation | {"PASS" if test.get('simulation_passed', False) else "FAIL"} |

### Validation

- [x] Code follows latest network specifications
- [x] Security baseline checks passed
- [x] Multi-device simulation tests passed
- [x] Telemetry/Prometheus instrumentation added where applicable

---
*This PR was automatically generated by the OpenClaw Ops Agent.*
"""
        return body
